/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_study_mp3lame_MainActivity */

#ifndef _Included_com_study_mp3lame_MainActivity
#define _Included_com_study_mp3lame_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_study_mp3lame_MainActivity
 * Method:    init
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_study_mp3lame_MainActivity_init
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_study_mp3lame_MainActivity
 * Method:    encode
 * Signature: ([S[SI[B)I
 */
JNIEXPORT jint JNICALL Java_com_study_mp3lame_MainActivity_encode
  (JNIEnv *, jclass, jshortArray, jshortArray, jint, jbyteArray);

/*
 * Class:     com_study_mp3lame_MainActivity
 * Method:    flush
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_study_mp3lame_MainActivity_flush
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_study_mp3lame_MainActivity
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_study_mp3lame_MainActivity_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
